#!/bin/bash

VERSION=${1}
DOCKERHUB_PASSWORD=${2}
DOCKERHUB_USERNAME=${3}

APP_NAME_AGENT_PRODUCTS=agent-products
APP_NAME_AGENT_INVOICES=agent-invoices
APP_NAME_AGENT_REPORTS=agent-reports
APP_NAME_AGENT_FRONTEND=agent-frontend

APP_IMAGE_NAME_AGENT_PRODUCTS=${DOCKERHUB_USERNAME}/${APP_NAME_AGENT_PRODUCTS}:${VERSION}
APP_IMAGE_NAME_AGENT_INVOICES=${DOCKERHUB_USERNAME}/${APP_NAME_AGENT_INVOICES}:${VERSION}
APP_IMAGE_NAME_AGENT_REPORTS=${DOCKERHUB_USERNAME}/${APP_NAME_AGENT_REPORTS}:${VERSION}
APP_IMAGE_NAME_AGENT_FRONTEND=${DOCKERHUB_USERNAME}/${APP_NAME_AGENT_FRONTEND}:${VERSION}

APP_ARTIFACT_NAME_AGENT_PRODUCTS=${APP_NAME_AGENT_PRODUCTS}:${VERSION}.tar
APP_ARTIFACT_NAME_AGENT_INVOICES=${APP_NAME_AGENT_INVOICES}:${VERSION}.tar
APP_ARTIFACT_NAME_AGENT_REPORTS=${APP_NAME_AGENT_REPORTS}:${VERSION}.tar
APP_ARTIFACT_NAME_AGENT_FRONTEND=${APP_NAME_AGENT_FRONTEND}:${VERSION}.tar

DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_AGENT_PRODUCTS}" \
--no-cache \
./agent-products

DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_AGENT_INVOICES}" \
--no-cache \
./agent-invoices

DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_AGENT_REPORTS}" \
--no-cache \
./agent-reports


DOCKER_BUILDKIT=1 docker build \
-t "${APP_IMAGE_NAME_AGENT_FRONTEND}" \
--no-cache \
./Frontend

docker save -o "$APP_ARTIFACT_NAME_AGENT_PRODUCTS" "$APP_IMAGE_NAME_AGENT_PRODUCTS"
docker save -o "$APP_ARTIFACT_NAME_AGENT_INVOICES" "$APP_IMAGE_NAME_AGENT_INVOICES"
docker save -o "$APP_ARTIFACT_NAME_AGENT_REPORTS" "$APP_IMAGE_NAME_AGENT_REPORTS"
docker save -o "$APP_ARTIFACT_NAME_AGENT_FRONTEND" "$APP_IMAGE_NAME_AGENT_FRONTEND"

docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_PASSWORD}
docker push "$APP_IMAGE_NAME_AGENT_PRODUCTS"
docker push "$APP_IMAGE_NAME_AGENT_INVOICES"
docker push "$APP_IMAGE_NAME_AGENT_REPORTS"
docker push "$APP_IMAGE_NAME_AGENT_FRONTEND"