version: '3.7'

services:
  # mysql-database:
  #   container_name: mysql-database
  #   image: mysql:8.0.19
  #   restart: always
  #   ports:
  #     - 3306
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
  #     interval: 3s
  #     retries: 5
  #     start_period: 30s
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=agentapplicationschema
  #   volumes:
  #     - ./data:/var/lib/mysql

  agent-products:
    container_name: agent-products
    image: agent-products:test
    build:
      dockerfile: Dockerfile.test
      context: ./agent-products

  # agent-reports:
  #   container_name: agent-reports
  #   build:
  #     context: ./agent-reports
  #   ports:
  #     - 8082
  #   depends_on:
  #     mysql-database:
  #         condition: service_healthy
  #   restart: on-failure
  #   environment:
  #     - mysql_username=root
  #     - mysql_password=root
  #     - mysql_host=mysql-database:3306
  #     - mysql_schema=agentapplicationschema

  # agent-invoices:
  #   container_name: agent-invoices
  #   build:
  #     context: ./agent-invoices
  #   ports:
  #     - 8083
  #   depends_on:
  #     mysql-database:
  #         condition: service_healthy
  #   restart: on-failure
  #   environment:
  #     - mysql_username=root
  #     - mysql_password=root
  #     - mysql_host=mysql-database:3306
  #     - mysql_schema=agentapplicationschema

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - agent-products
  #     - agent-invoices
  #     - agent-reports

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./Frontend
  #   ports:
  #     - 3000:3000