version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul
    command: 'consul agent -ui -server -bootstrap -data-dir=/tmp/consul -node=agent-one -client=0.0.0.0 -enable-script-checks=true -config-dir=/etc/consul.d'
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600/udp
    volumes:
      - ./consul.d:/etc/consul.d
    environment:
     - CONSUL_BIND_INTERFACE=eth0

  agent-gateway:
    container_name: agent-gateway
    build:
      context: ./agent-gateway
    ports:
      - 8080:8080
    depends_on:
      consul:
        condition: service_started  

  mysql-database:
    container_name: mysql-database
    image: mysql:8.0.19
    restart: always
    ports:
      - 3306:3306
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=agentapplicationschema
    volumes:
      - ./data:/var/lib/mysql

  agent-products:
    container_name: agent-products
    build:
      context: ./agent-products
    ports:
      - 8081:8081
    depends_on:
      consul:
        condition: service_started
      mysql-database:
          condition: service_healthy
    restart: on-failure
    environment:
      - mysql_username=root
      - mysql_password=root
      - mysql_host=mysql-database:3306
      - mysql_schema=agentapplicationschema
