name: Run unit tests
on: 
  pull_request:
    branches:
        - main
        - development
    types: [opened, synchronize]

jobs:     
  # Run unit tests
  unit-test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run unit tests
      working-directory: ./Backend
      run: go test ./..